### ISSUE TITLE
random test failure - error stopping collaboration pinner test collab: { ReadError: Database is not open

### ISSUE THREAD

**Issue by jimpick** [ipfs-shipyard/peer-star-app#161]
Another random test failure I've seen a few times:

```
  replication
Swarm listening on /ip4/127.0.0.1/tcp/9090/ws/p2p-websocket-star/ipfs/QmPcjXb8MsY5xBuPho4DhFKEqE8XJMhqnxKNetJCeTFiDe
Swarm listening on /ip4/127.0.0.1/tcp/9090/ws/p2p-websocket-star/ipfs/QmSCNvYHFa3eKmjMWJMW2TUBcguSAudBAvyxXxojgKC7iP
Swarm listening on /ip4/127.0.0.1/tcp/9090/ws/p2p-websocket-star/ipfs/QmWP8SDQ7fE1kPkqL2pAeE6sFsz7Unbe6ab79tL5afXYyf
pinner for "4e8b1FXGsCt5bcCHPXaUGv4UKsApsAEK8v49daPRmRiM" started
No options.keys
    ✓ can add a pinner to a collaboration (7763ms)
error stopping collaboration pinner test collab: { ReadError: Database is not open
    at maybeError (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/node_modules/levelup/lib/levelup.js:306:32)
    at LevelUP.put (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/node_modules/levelup/lib/levelup.js:191:7)
    at LevelDatastore.put (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/node_modules/datastore-level/src/index.js:63:13)
    at NamespaceDatastore.put (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/node_modules/datastore-core/src/keytransform.js:46:16)
    at Promise (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/src/collaboration/store.js:29:19)
    at new Promise (<anonymous>)
    at Store._saveRaw (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/src/collaboration/store.js:28:12)
    at Store.save (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/src/collaboration/store.js:24:17) code: 'ERR_DB_WRITE_FAILED' }
    1) waits for replication events
    ✓ converged between replicas
    ✓ can stop pinner

  local-persistence
Swarm listening on /ip4/127.0.0.1/tcp/9090/ws/p2p-websocket-star/ipfs/QmWEe9vNsLb2oP6BsYb7xNNpi97fqmEigVCNtEQvFnV9MZ
No options.keys
    ✓ can create collaboration and populate it (933ms)
Swarm listening on /ip4/127.0.0.1/tcp/9090/ws/p2p-websocket-star/ipfs/QmWEe9vNsLb2oP6BsYb7xNNpi97fqmEigVCNtEQvFnV9MZ
No options.keys
error stopping collaboration pinner test collab: { ReadError: Database is not open
    at maybeError (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/node_modules/levelup/lib/levelup.js:306:32)
    at LevelUP.put (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/node_modules/levelup/lib/levelup.js:191:7)
    at LevelDatastore.put (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/node_modules/datastore-level/src/index.js:63:13)
    at NamespaceDatastore.put (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/node_modules/datastore-core/src/keytransform.js:46:16)
    at Promise (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/src/collaboration/store.js:29:19)
    at new Promise (<anonymous>)
    at Store._saveRaw (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/src/collaboration/store.js:28:12)
    at Store.save (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/src/collaboration/store.js:24:17) code: 'ERR_DB_WRITE_FAILED' }
    ✓ can revive collaboration from ipfs repo (2093ms)

  handling data
    ✓ correctly decodes data
    ✓ sets error argument if the data is incorrectly encoded
    ✓ sets error argument if the handler function throws an error


  111 passing (6m)
  1 failing

  1) replication
       waits for replication events:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/test/node.js)




Command failed: mocha --timeout 5000 --ui bdd --colors --exit test/node.js test/**/*.spec.js
null
null
Error: Command failed: mocha --timeout 5000 --ui bdd --colors --exit test/node.js test/**/*.spec.js
null
null
    at makeError (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peer-star-app@0.10.2 test:node: `aegir test -t node`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peer-star-app@0.10.2 test:node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

```
$ uname -a
Darwin jpmbp2.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64
$ node -v
v10.13.0
```

**Comment by pgte** [comment]
I haven't seen this in the wild. Please reopen this if you find this is not the case.

**Comment by jimpick** [comment]
Possibly this was also due to my using my own js-ipfs build... I was trying to suppress all those "Swarm listening on..." console messages that trash the unit test output. It should have matched the 0.33.1 build, but something must not have matched.
